version: '3.8'
services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: protonvpn
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    volumes:
      - ./protonvpn.conf:/gluetun/config.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - HTTPPROXY=off
      - KILL_SWITCH=on
    dns:
      - 10.2.0.1
    healthcheck:
      test: ["CMD-SHELL", "curl -s https://icanhazip.com"]
      interval: 60s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: yt-downloader
    depends_on:
      vpn:
        condition: service_healthy
    network_mode: service:protonvpn
    volumes:
      - ./cookies.txt:/app/cookies.txt:ro
      - ./downloads:/app/downloads
    environment:
      - COOKIES_FILE=/app/cookies.txt
    ports:
      - "5000:5000"
    restart: unless-stopped
